ci: Build and push the helm chart as OCI image (#203)
* ci: Build and push the helm chart as OCI image

Also make oci-images build to depend on verify

* Fix image name

* Add step waiting all oci-images to be built

This is useful as it uses stable static name so that it can be used as
required PR status check

* Rename non-release workflow to Non-Release

* Fix charts repository to not duplicate gardener-discovery-server in its path

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -24,6 +24,7 @@ jobs:
     name: Build OCI-Images
     needs:
       - prepare
+      - verify
     permissions:
       contents: read
       packages: write
@@ -54,6 +55,19 @@ jobs:
       ocm-labels: ${{ toJSON(matrix.args.ocm-labels) }}
       target: ${{ matrix.args.target }}
       extra-tags: latest
+
+  oci-images-summary:
+    name: OCI Images Summary
+    runs-on: ubuntu-latest
+    needs:
+    - oci-images
+    if: ${{ always() }}  # Ensures this job runs even if the matrix partially fails
+    permissions:
+      contents: read
+    steps:
+      - name: Fail if OCI matrix failed
+        if: ${{ needs.oci-images.result != 'success' }}
+        run: exit 1
 
   verify:
     runs-on: ubuntu-latest
@@ -102,3 +116,44 @@ jobs:
                 - name: gardener.cloud/purposes
                   value:
                     - test
+
+  helmcharts:
+    name: Build Helmcharts
+    needs:
+      - prepare
+      - oci-images
+    permissions:
+      contents: read
+      packages: write
+      id-token: write
+    uses: gardener/cc-utils/.github/workflows/helmchart-ocm.yaml@v1
+    strategy:
+      matrix:
+        args:
+          - name: gardener-discovery-server
+            dir: charts/discovery-server
+            oci-repository: charts/gardener
+            ocm-mappings:
+              - ref: ocm-resource:gardener-discovery-server.repository
+                attribute: runtime.image.repository
+              - ref: ocm-resource:gardener-discovery-server.tag
+                attribute: runtime.image.tag
+    with:
+      name: ${{ matrix.args.name }}
+      dir: ${{ matrix.args.dir }}
+      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
+      oci-repository: ${{ matrix.args.oci-repository }}
+      ocm-mappings: ${{ toJSON(matrix.args.ocm-mappings) }}
+
+  helmcharts-summary:
+    name: Helm Charts Summary
+    runs-on: ubuntu-latest
+    needs:
+    - helmcharts
+    if: ${{ always() }}  # Ensures this job runs even if the matrix partially fails
+    permissions:
+      contents: read
+    steps:
+      - name: Fail if Helm Charts matrix failed
+        if: ${{ needs.helmcharts.result != 'success' }}
+        run: exit 1
